### PR TITLE
Adds more ohai network reload notifications

### PR DESCRIPTION
**Pull request by zedtux**
The AutoIP feature of this cookbook rely on the node's network setup in order to check if a previously generated IP address is present on the tinc network interface.
The missing notifications to the ohai 'reload_network', that this commit add, make the cookbook regenerating a new IP address on converge, which is an issue when other cookbooks are using it.

### CODE REVIEW

**Comment by zedtux** [comment]
Not sure why the build failed for docker :shrug:

**Comment by zedtux** [comment]
I can confirm that this change fixes the issue I had. I did like 5 converges since, and the IP address is now stable.

**Comment by EugenMayer** [comment]
seems like the test has no failures, it seems to be an exit code issue or something else

**Comment by zedtux** [comment]
Let's trigger another build ...

**Pull request merged**
