### PR TITLE
Warns when avahi is enabled and network name is too long (Closes #13)

### LINKED ISSUE #13: Avahi fails when network name is too long - should add a warning?
I was using the network name `kubernetes-staging` and got the issue that Avahi never get an IPv4 address.

I found this ticket ubuntu issue [avahi-autoipd fails because network interface name is too long](https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/1666900) so I tried to rename my network to `k8sstg` and now it works.

I have noticed that the network name `kubernetes-staging` was always truncated to `kubernetes-stag` which has a length of 15, so we could add a warning message when the network name is longer than 15.

### PR DESCRIPTION
**Pull request by zedtux**

### CODE REVIEW

**Comment by EugenMayer** [comment]
.. Thank you :)

**Comment by zedtux** [comment]
So that was my last contribution as far as I can tell.

Would you mind to release a new version of the cookbook on the supermarket please?

**Comment by EugenMayer** [comment]
Sure - i think considering the amount of features and changes we should go with at least a minor, if not rather a Major release. What do you think?

**Comment by zedtux** [comment]
I'm for the Major release.

**Pull request merged**
