### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by mrvovanness**
Refactor default recipe by adding several custom resources:
- attributes_publishing - manage publishing node tincvpn attributes to chef-server
- host_config - manages configs in /etc/tinc/net_name/hosts
- interface_up_down - manages tinc-up and tinc-down
- interface_up_down_avahi_zeroconf - manages zeroconf interface creation
- keypair - manages creation of keypair
- main_config - manages tinc.conf for network
Above resources can be used separately without applying default recipe

Add specs for custom network creation

Add ubuntu 16 to test suite

Add new info to readme regarding how to use this cookbook

Remove dependency on openssl cookbook

### CODE REVIEW

**Comment by EugenMayer** [comment]
Sorry but this is a huge PR without any communication upgront also bundle a gazzilion different topics in one. 

why didn't you bother to actually go for a discussion first? I am not against improving or using custom resource, but those huge PRs without any pre-talks are doomed to fail.

**Comment by EugenMayer** [comment]
how is refactoring going for you, what are your plans here (or issues) whats the initial motivation?

**Comment by mrvovanness** [comment]
I started refactoring because I wanted more granular control and default recipe was not enough :) Also code is hard to read because it is not divided on logical part. But anyway, I can close it for now and open new PRs with smaller changes :)

**Comment by EugenMayer** [comment]
i guess that one is dead for now - feel free to continue the effort enytime

**Pull request closed without merging**
